modLoader="javafml"
loaderVersion="${forgeLoaderRange}"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/MythLib/issues"

[[mods]]
modId="mythlib"
version="${modVersion}"
displayName="MythLib"
#updateJSONURL="http://myurl.me/"
#displayURL="https://example.example"
#logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
authors="TonimatasDEV"
#displayTest="MATCH_VERSION"

description='''
Cross-Platform library.
'''

[[dependencies.mythlib]]
   modId="forge"
   mandatory=true
   versionRange="${forgeLoaderRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.mythlib]]
   modId="minecraft"
   mandatory=true
   versionRange="${forgeMinecraftVersionRange}"
   ordering="NONE"
   side="BOTH"