name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3.5.2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 17

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: build

    - name: Publish
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: publish
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.PASSWORD }}
