name: Java with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build jar

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: MythLib-Forge
          path: forge/build/libs/**.jar

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: MythLib-Fabric
          path: fabric/build/libs/**.jar
